"""
Configuration for Resume-JD NLP Pipeline
=========================================
Central config for model parameters, scoring weights, 
skill taxonomies, and normalization mappings.
"""

# ─── Model Configuration ────────────────────────────────────────────────────────
SBERT_MODEL_NAME = "all-MiniLM-L6-v2"  # Sentence-BERT model for semantic embeddings
SIMILARITY_THRESHOLD_STRONG = 0.75     # Cosine similarity >= this → strong match
SIMILARITY_THRESHOLD_PARTIAL = 0.45    # Cosine similarity >= this → partial match

# ─── Scoring Weights (must sum to 100) ───────────────────────────────────────────
WEIGHT_SEMANTIC_SIMILARITY = 35
WEIGHT_SKILL_MATCH = 30
WEIGHT_EXPERIENCE_MATCH = 20
WEIGHT_DOMAIN_SIMILARITY = 15

# ─── Skill Normalization Map ─────────────────────────────────────────────────────
# Maps abbreviations and alternate names to canonical forms
SKILL_NORMALIZATION = {
    # Programming Languages
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "py": "Python",
    "python": "Python",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "golang": "Go",
    "go": "Go",
    "rb": "Ruby",
    "ruby": "Ruby",
    "rs": "Rust",
    "rust": "Rust",
    "kt": "Kotlin",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "r": "R",
    "matlab": "MATLAB",
    "scala": "Scala",
    "perl": "Perl",
    "php": "PHP",
    "dart": "Dart",
    "lua": "Lua",
    "shell": "Shell Scripting",
    "bash": "Shell Scripting",
    "powershell": "PowerShell",
    "sql": "SQL",
    "nosql": "NoSQL",
    "html": "HTML",
    "css": "CSS",
    "sass": "SASS/SCSS",
    "scss": "SASS/SCSS",

    # ML / AI / Data Science
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "keras": "Keras",
    "scikit-learn": "Scikit-Learn",
    "sklearn": "Scikit-Learn",
    "scikit learn": "Scikit-Learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "opencv": "OpenCV",
    "cv2": "OpenCV",
    "spacy": "spaCy",
    "nltk": "NLTK",
    "huggingface": "Hugging Face Transformers",
    "hugging face": "Hugging Face Transformers",
    "transformers": "Hugging Face Transformers",
    "bert": "BERT",
    "gpt": "GPT",
    "llm": "Large Language Models",
    "llms": "Large Language Models",
    "langchain": "LangChain",
    "rag": "Retrieval Augmented Generation",
    "mlflow": "MLflow",
    "wandb": "Weights & Biases",
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "dl": "Deep Learning",
    "nlp": "Natural Language Processing",
    "natural language processing": "Natural Language Processing",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "reinforcement learning": "Reinforcement Learning",
    "rl": "Reinforcement Learning",
    "generative ai": "Generative AI",
    "gen ai": "Generative AI",
    "genai": "Generative AI",
    "data science": "Data Science",
    "data analysis": "Data Analysis",
    "data engineering": "Data Engineering",
    "feature engineering": "Feature Engineering",
    "model deployment": "Model Deployment",
    "mlops": "MLOps",
    "neural network": "Neural Networks",
    "neural networks": "Neural Networks",
    "cnn": "Convolutional Neural Networks",
    "rnn": "Recurrent Neural Networks",
    "lstm": "LSTM",
    "gan": "Generative Adversarial Networks",
    "automl": "AutoML",

    # Web Frameworks
    "react": "React",
    "reactjs": "React",
    "react.js": "React",
    "angular": "Angular",
    "angularjs": "Angular",
    "vue": "Vue.js",
    "vuejs": "Vue.js",
    "vue.js": "Vue.js",
    "svelte": "Svelte",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nuxt": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "gatsby": "Gatsby",
    "remix": "Remix",

    # Backend / Server
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "express": "Express.js",
    "expressjs": "Express.js",
    "express.js": "Express.js",
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "spring": "Spring Boot",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "rails": "Ruby on Rails",
    "ruby on rails": "Ruby on Rails",
    "asp.net": "ASP.NET",
    "aspnet": "ASP.NET",
    "graphql": "GraphQL",
    "rest": "REST API",
    "rest api": "REST API",
    "restful": "REST API",
    "grpc": "gRPC",
    "microservices": "Microservices",

    # Databases
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "dynamodb": "DynamoDB",
    "cassandra": "Cassandra",
    "sqlite": "SQLite",
    "firebase": "Firebase",
    "firestore": "Firestore",
    "supabase": "Supabase",
    "neo4j": "Neo4j",
    "oracle": "Oracle DB",
    "mssql": "MS SQL Server",
    "sql server": "MS SQL Server",

    # Cloud / DevOps
    "aws": "Amazon Web Services",
    "amazon web services": "Amazon Web Services",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "azure": "Microsoft Azure",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "jenkins": "Jenkins",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "circleci": "CircleCI",
    "devops": "DevOps",
    "linux": "Linux",
    "nginx": "NGINX",
    "apache": "Apache",
    "serverless": "Serverless Architecture",
    "lambda": "AWS Lambda",
    "cloudformation": "CloudFormation",
    "s3": "Amazon S3",
    "ec2": "Amazon EC2",
    "ecs": "Amazon ECS",
    "eks": "Amazon EKS",
    "sagemaker": "Amazon SageMaker",

    # Data Tools
    "spark": "Apache Spark",
    "pyspark": "PySpark",
    "hadoop": "Hadoop",
    "kafka": "Apache Kafka",
    "airflow": "Apache Airflow",
    "dbt": "dbt",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "redshift": "Amazon Redshift",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "looker": "Looker",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "scipy": "SciPy",
    "excel": "Microsoft Excel",
    "etl": "ETL",

    # Mobile
    "react native": "React Native",
    "flutter": "Flutter",
    "ios": "iOS Development",
    "android": "Android Development",
    "swiftui": "SwiftUI",
    "jetpack compose": "Jetpack Compose",

    # Testing
    "jest": "Jest",
    "mocha": "Mocha",
    "pytest": "Pytest",
    "junit": "JUnit",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "unittest": "Unit Testing",
    "unit testing": "Unit Testing",
    "integration testing": "Integration Testing",
    "tdd": "Test-Driven Development",

    # Version Control / Tools
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "jira": "Jira",
    "confluence": "Confluence",
    "slack": "Slack",
    "figma": "Figma",
    "postman": "Postman",
    "swagger": "Swagger/OpenAPI",
    "openapi": "Swagger/OpenAPI",

    # Security
    "oauth": "OAuth",
    "jwt": "JWT",
    "ssl": "SSL/TLS",
    "encryption": "Encryption",
    "cybersecurity": "Cybersecurity",
    "penetration testing": "Penetration Testing",
    "owasp": "OWASP",

    # Methodologies
    "agile": "Agile",
    "scrum": "Scrum",
    "kanban": "Kanban",
    "waterfall": "Waterfall",
    "lean": "Lean",
    "sdlc": "SDLC",
    "oop": "Object-Oriented Programming",
    "functional programming": "Functional Programming",
    "design patterns": "Design Patterns",
    "solid": "SOLID Principles",
    "system design": "System Design",
    "dsa": "Data Structures & Algorithms",
    "data structures": "Data Structures & Algorithms",
    "algorithms": "Data Structures & Algorithms",
}

# ─── Skill Taxonomy (semantic groupings for domain inference) ─────────────────
SKILL_DOMAINS = {
    "Machine Learning / AI": [
        "Machine Learning", "Deep Learning", "Neural Networks", "PyTorch", "TensorFlow",
        "Keras", "Scikit-Learn", "XGBoost", "LightGBM", "Computer Vision",
        "Natural Language Processing", "BERT", "GPT", "Large Language Models",
        "Generative AI", "LangChain", "Retrieval Augmented Generation", "MLOps",
        "MLflow", "Weights & Biases", "Convolutional Neural Networks",
        "Recurrent Neural Networks", "LSTM", "Generative Adversarial Networks",
        "Reinforcement Learning", "AutoML", "OpenCV", "spaCy", "NLTK",
        "Hugging Face Transformers", "Amazon SageMaker", "Feature Engineering",
        "Model Deployment",
    ],
    "Data Science / Analytics": [
        "Data Science", "Data Analysis", "Pandas", "NumPy", "Matplotlib",
        "Seaborn", "Plotly", "SciPy", "R", "MATLAB", "Tableau", "Power BI",
        "Looker", "Microsoft Excel", "Statistics", "Data Visualization",
        "BigQuery", "Snowflake", "ETL",
    ],
    "Data Engineering": [
        "Data Engineering", "Apache Spark", "PySpark", "Hadoop", "Apache Kafka",
        "Apache Airflow", "dbt", "Snowflake", "BigQuery", "Amazon Redshift",
        "ETL", "SQL", "NoSQL",
    ],
    "Frontend Development": [
        "React", "Angular", "Vue.js", "Svelte", "Next.js", "Nuxt.js", "Gatsby",
        "Remix", "JavaScript", "TypeScript", "HTML", "CSS", "SASS/SCSS",
        "Figma", "Responsive Design",
    ],
    "Backend Development": [
        "Node.js", "Express.js", "FastAPI", "Django", "Flask", "Spring Boot",
        "Ruby on Rails", "ASP.NET", "GraphQL", "REST API", "gRPC",
        "Microservices", "Python", "Java", "Go", "Rust", "C#",
    ],
    "Full-Stack Development": [
        "React", "Angular", "Vue.js", "Node.js", "Express.js", "Next.js",
        "Django", "Flask", "REST API", "GraphQL", "MongoDB", "PostgreSQL",
        "JavaScript", "TypeScript",
    ],
    "Cloud / DevOps": [
        "Amazon Web Services", "Google Cloud Platform", "Microsoft Azure",
        "Docker", "Kubernetes", "Terraform", "Ansible", "Jenkins", "CI/CD",
        "GitHub Actions", "GitLab CI", "DevOps", "Linux", "NGINX",
        "Serverless Architecture", "AWS Lambda", "CloudFormation",
        "Amazon S3", "Amazon EC2", "Amazon ECS", "Amazon EKS",
    ],
    "Mobile Development": [
        "React Native", "Flutter", "iOS Development", "Android Development",
        "SwiftUI", "Jetpack Compose", "Swift", "Kotlin", "Dart",
    ],
    "Cybersecurity": [
        "Cybersecurity", "Penetration Testing", "OWASP", "OAuth", "JWT",
        "SSL/TLS", "Encryption",
    ],
}

# ─── Experience Level Indicators ─────────────────────────────────────────────────
EXPERIENCE_KEYWORDS = {
    "fresher": [
        "fresher", "intern", "internship", "entry level", "entry-level",
        "recent graduate", "new grad", "no experience", "student",
        "undergraduate", "pursuing", "0 years", "trainee",
    ],
    "junior": [
        "junior", "associate", "1 year", "2 years", "1-2 years",
        "0-2 years", "1+ year", "early career",
    ],
    "mid": [
        "mid", "mid-level", "3 years", "4 years", "5 years",
        "3-5 years", "2-5 years", "3+ years", "experienced",
    ],
    "senior": [
        "senior", "lead", "principal", "staff", "architect",
        "6 years", "7 years", "8 years", "9 years", "10 years",
        "5+ years", "6+ years", "7+ years", "8+ years", "10+ years",
        "15+ years", "manager", "director", "head of", "vp ",
        "vice president",
    ],
}

# ─── Role Normalization ──────────────────────────────────────────────────────────
ROLE_KEYWORDS = {
    "Software Engineer": ["software engineer", "software developer", "swe", "sde"],
    "Backend Developer": ["backend developer", "backend engineer", "server-side"],
    "Frontend Developer": ["frontend developer", "frontend engineer", "ui developer", "ui engineer"],
    "Full-Stack Developer": ["full stack", "full-stack", "fullstack"],
    "ML Engineer": ["machine learning engineer", "ml engineer", "ai engineer", "ai/ml"],
    "Data Scientist": ["data scientist", "data science"],
    "Data Engineer": ["data engineer", "data engineering"],
    "Data Analyst": ["data analyst", "business analyst", "analytics"],
    "DevOps Engineer": ["devops engineer", "devops", "site reliability", "sre"],
    "Cloud Engineer": ["cloud engineer", "cloud architect", "solutions architect"],
    "Mobile Developer": ["mobile developer", "android developer", "ios developer", "mobile engineer"],
    "Product Manager": ["product manager", "pm", "product owner"],
    "QA Engineer": ["qa engineer", "quality assurance", "test engineer", "sdet"],
    "Security Engineer": ["security engineer", "cybersecurity", "infosec"],
    "Research Scientist": ["research scientist", "researcher", "research engineer"],
}
