"""
Model Training Script
======================
Trains a regression model to predict resume-JD match scores from
extracted NLP features.

Training Pipeline:
  1. Load feature CSV (semantic_similarity, skill_match, experience, domain -> score)
  2. Split into train/test (80/20, stratified by score bins)
  3. Train LinearRegression as baseline
  4. Train XGBRegressor as primary model
  5. Evaluate both using R2, MSE, MAE
  6. Save the best model as model.pkl via joblib
  7. Save training metadata as model_metadata.json

Usage:
  python train_model.py                         # Train on default CSV
  python train_model.py --csv my_data.csv       # Train on custom CSV
  python train_model.py --generate 500          # Generate synthetic data first, then train
"""

import os
import sys
import json
import time
import argparse
import numpy as np
import pandas as pd
import joblib
from datetime import datetime

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    mean_absolute_error,
)
from sklearn.preprocessing import StandardScaler

# ─── Paths ───────────────────────────────────────────────────────────────────────
ML_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CSV = os.path.join(ML_DIR, "ml_training_data.csv")
MODEL_PATH = os.path.join(ML_DIR, "model.pkl")
SCALER_PATH = os.path.join(ML_DIR, "scaler.pkl")
METADATA_PATH = os.path.join(ML_DIR, "model_metadata.json")

FEATURE_COLUMNS = ["semantic_similarity", "skill_match", "experience", "domain"]
TARGET_COLUMN = "score"


def generate_synthetic_training_data(n_samples: int = 500, csv_path: str = DEFAULT_CSV) -> str:
    """
    Generate realistic synthetic training data using the heuristic scoring formula
    with controlled noise to create diverse, learnable patterns.

    The synthetic data is generated by:
      1. Sampling feature vectors from realistic distributions
      2. Computing heuristic scores using the existing weighted formula
      3. Adding Gaussian noise to simulate real-world variation
      4. Injecting non-linear interaction effects (which the ML model should learn)

    Args:
        n_samples: Number of training samples to generate
        csv_path: Path to save the CSV

    Returns:
        Path to the generated CSV
    """
    print(f"\n{'='*60}")
    print(f"  Generating {n_samples} Synthetic Training Samples")
    print(f"{'='*60}")

    np.random.seed(42)

    # ── Feature distributions modeled from real resume-JD analysis ────────
    # Semantic similarity: Beta distribution (peaks around 0.4-0.7)
    sem_sim = np.random.beta(3, 3, n_samples)                      # [0, 1]

    # Skill match: Mixture of low and high matches
    skill_match = np.clip(
        np.concatenate([
            np.random.beta(2, 5, n_samples // 3),         # Low match candidates
            np.random.beta(5, 3, n_samples // 3),          # High match candidates
            np.random.beta(3, 3, n_samples - 2 * (n_samples // 3)),  # Medium
        ]),
        0, 1,
    )
    np.random.shuffle(skill_match)

    # Experience match: Discrete-like (0.1, 0.3, 0.55, 0.6, 0.7, 1.0)
    exp_values = [0.1, 0.25, 0.3, 0.55, 0.6, 0.7, 1.0]
    exp_probs = [0.08, 0.07, 0.12, 0.13, 0.15, 0.15, 0.30]
    experience = np.random.choice(exp_values, n_samples, p=exp_probs)
    # Add small jitter
    experience = np.clip(experience + np.random.normal(0, 0.03, n_samples), 0, 1)

    # Domain similarity: Bimodal (either matches or doesn't)
    domain = np.clip(
        np.concatenate([
            np.random.beta(1.5, 5, n_samples // 2),     # Mismatches
            np.random.beta(5, 1.5, n_samples // 2),      # Matches
        ]),
        0, 1,
    )
    np.random.shuffle(domain)

    # ── Compute scores with the heuristic formula + non-linear effects ────
    # Base heuristic score
    base_score = (
        sem_sim * 35 +
        skill_match * 30 +
        experience * 20 +
        domain * 15
    )

    # Add non-linear interaction effects the ML model should learn:
    # 1. Skill-domain synergy: high skill + high domain = bonus
    synergy_bonus = 3.0 * (skill_match * domain)

    # 2. Experience-semantic interaction: experienced + semantic match = bonus
    exp_sem_bonus = 2.5 * (experience * sem_sim)

    # 3. Penalty for low skill match regardless of other features
    low_skill_penalty = np.where(skill_match < 0.2, -5.0, 0.0)

    # 4. Domain mismatch amplification
    domain_penalty = np.where(domain < 0.15, -3.0, 0.0)

    # Combine
    score = base_score + synergy_bonus + exp_sem_bonus + low_skill_penalty + domain_penalty

    # Add realistic noise
    noise = np.random.normal(0, 2.5, n_samples)
    score = np.clip(score + noise, 0, 100)

    # ── Build DataFrame ───────────────────────────────────────────────────
    df = pd.DataFrame({
        "semantic_similarity": np.round(sem_sim, 6),
        "skill_match": np.round(skill_match, 6),
        "experience": np.round(experience, 6),
        "domain": np.round(domain, 6),
        "score": np.round(score, 4),
        "timestamp": [
            datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            for _ in range(n_samples)
        ],
    })

    # ── Save ──────────────────────────────────────────────────────────────
    df.to_csv(csv_path, index=False)
    print(f"  Saved to: {csv_path}")
    print(f"  Samples:  {len(df)}")
    print(f"\n  Feature Statistics:")
    print(f"  {'Feature':<25} {'Mean':>8} {'Std':>8} {'Min':>8} {'Max':>8}")
    print(f"  {'-'*57}")
    for col in FEATURE_COLUMNS + [TARGET_COLUMN]:
        print(f"  {col:<25} {df[col].mean():>8.4f} {df[col].std():>8.4f} "
              f"{df[col].min():>8.4f} {df[col].max():>8.4f}")

    return csv_path


def load_data(csv_path: str) -> tuple:
    """
    Load and validate the training CSV.

    Returns:
        Tuple of (X: DataFrame, y: Series, df: DataFrame)
    """
    print(f"\n[1/5] Loading data from: {csv_path}")

    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Training data not found: {csv_path}\n"
            f"Run with --generate flag to create synthetic data, or "
            f"run the pipeline on resume-JD pairs to collect data."
        )

    df = pd.read_csv(csv_path)

    # Validate columns
    missing = [c for c in FEATURE_COLUMNS + [TARGET_COLUMN] if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns in CSV: {missing}")

    # Drop rows with NaN
    initial_count = len(df)
    df = df.dropna(subset=FEATURE_COLUMNS + [TARGET_COLUMN])
    if len(df) < initial_count:
        print(f"  Dropped {initial_count - len(df)} rows with NaN values")

    X = df[FEATURE_COLUMNS]
    y = df[TARGET_COLUMN]

    print(f"  Total samples: {len(df)}")
    print(f"  Features: {list(X.columns)}")
    print(f"  Target range: [{y.min():.2f}, {y.max():.2f}]")
    print(f"  Target mean: {y.mean():.2f}, std: {y.std():.2f}")

    if len(df) < 20:
        print("  WARNING: Very few training samples. Model may not generalize well.")

    return X, y, df


def train_and_evaluate(X: pd.DataFrame, y: pd.Series) -> dict:
    """
    Train both LinearRegression and XGBRegressor, evaluate, and return results.

    Pipeline:
      1. Train-test split (80/20)
      2. Fit StandardScaler on train set
      3. Train LinearRegression (baseline)
      4. Train XGBRegressor (primary)
      5. 5-fold cross-validation on both
      6. Compare and select best model

    Returns:
        Dict with best model, scaler, and evaluation metrics
    """
    print(f"\n[2/5] Splitting data (80/20 train-test split)...")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    print(f"  Train: {len(X_train)} samples | Test: {len(X_test)} samples")

    # ── Scale features ────────────────────────────────────────────────────
    print(f"\n[3/5] Fitting StandardScaler...")
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print(f"  Feature means (train): {np.round(scaler.mean_, 4)}")
    print(f"  Feature stds  (train): {np.round(scaler.scale_, 4)}")

    results = {}

    # ── Model 1: LinearRegression (Baseline) ──────────────────────────────
    print(f"\n[4/5] Training models...")
    print(f"\n  --- LinearRegression (Baseline) ---")

    lr_model = LinearRegression()
    lr_model.fit(X_train_scaled, y_train)

    y_pred_lr = lr_model.predict(X_test_scaled)
    y_pred_lr = np.clip(y_pred_lr, 0, 100)

    lr_r2 = r2_score(y_test, y_pred_lr)
    lr_mse = mean_squared_error(y_test, y_pred_lr)
    lr_mae = mean_absolute_error(y_test, y_pred_lr)

    # Cross-validation
    lr_cv_scores = cross_val_score(
        lr_model, scaler.transform(X), y, cv=5, scoring="r2"
    )

    print(f"  R2 Score:       {lr_r2:.6f}")
    print(f"  MSE:            {lr_mse:.6f}")
    print(f"  MAE:            {lr_mae:.6f}")
    print(f"  RMSE:           {np.sqrt(lr_mse):.6f}")
    print(f"  CV R2 (5-fold): {lr_cv_scores.mean():.6f} (+/- {lr_cv_scores.std():.6f})")
    print(f"  Coefficients:   {dict(zip(FEATURE_COLUMNS, np.round(lr_model.coef_, 4)))}")
    print(f"  Intercept:      {lr_model.intercept_:.4f}")

    results["linear_regression"] = {
        "model": lr_model,
        "r2": lr_r2,
        "mse": lr_mse,
        "mae": lr_mae,
        "rmse": float(np.sqrt(lr_mse)),
        "cv_r2_mean": float(lr_cv_scores.mean()),
        "cv_r2_std": float(lr_cv_scores.std()),
        "coefficients": dict(zip(FEATURE_COLUMNS, lr_model.coef_.tolist())),
        "intercept": float(lr_model.intercept_),
    }

    # ── Model 2: XGBRegressor (Primary) ───────────────────────────────────
    print(f"\n  --- XGBRegressor (Primary) ---")

    try:
        from xgboost import XGBRegressor

        xgb_model = XGBRegressor(
            n_estimators=200,
            max_depth=4,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            reg_alpha=0.1,       # L1 regularization
            reg_lambda=1.0,      # L2 regularization
            min_child_weight=3,  # Prevent overfitting
            random_state=42,
            verbosity=0,
        )

        xgb_model.fit(
            X_train_scaled, y_train,
            eval_set=[(X_test_scaled, y_test)],
            verbose=False,
        )

        y_pred_xgb = xgb_model.predict(X_test_scaled)
        y_pred_xgb = np.clip(y_pred_xgb, 0, 100)

        xgb_r2 = r2_score(y_test, y_pred_xgb)
        xgb_mse = mean_squared_error(y_test, y_pred_xgb)
        xgb_mae = mean_absolute_error(y_test, y_pred_xgb)

        # Cross-validation
        xgb_cv = XGBRegressor(
            n_estimators=200, max_depth=4, learning_rate=0.1,
            subsample=0.8, colsample_bytree=0.8,
            reg_alpha=0.1, reg_lambda=1.0, min_child_weight=3,
            random_state=42, verbosity=0,
        )
        xgb_cv_scores = cross_val_score(
            xgb_cv, scaler.transform(X), y, cv=5, scoring="r2"
        )

        # Feature importance
        importances = dict(zip(
            FEATURE_COLUMNS,
            np.round(xgb_model.feature_importances_, 4).tolist(),
        ))

        print(f"  R2 Score:       {xgb_r2:.6f}")
        print(f"  MSE:            {xgb_mse:.6f}")
        print(f"  MAE:            {xgb_mae:.6f}")
        print(f"  RMSE:           {np.sqrt(xgb_mse):.6f}")
        print(f"  CV R2 (5-fold): {xgb_cv_scores.mean():.6f} (+/- {xgb_cv_scores.std():.6f})")
        print(f"  Feature Importance: {importances}")

        results["xgboost"] = {
            "model": xgb_model,
            "r2": xgb_r2,
            "mse": xgb_mse,
            "mae": xgb_mae,
            "rmse": float(np.sqrt(xgb_mse)),
            "cv_r2_mean": float(xgb_cv_scores.mean()),
            "cv_r2_std": float(xgb_cv_scores.std()),
            "feature_importance": importances,
        }

    except ImportError:
        print("  XGBoost not installed. Skipping.")
        print("  Install with: pip install xgboost")

    return results, scaler, X_test, y_test


def select_and_save_best(results: dict, scaler, csv_path: str) -> str:
    """
    Select the best model and save it along with the scaler and metadata.

    Returns:
        Name of the selected model
    """
    print(f"\n[5/5] Selecting and saving best model...")

    # Compare models by cross-validated R2
    best_name = None
    best_cv_r2 = -float("inf")

    print(f"\n  {'Model':<25} {'Test R2':>10} {'CV R2':>10} {'RMSE':>10}")
    print(f"  {'-'*55}")

    for name, metrics in results.items():
        cv_r2 = metrics["cv_r2_mean"]
        print(f"  {name:<25} {metrics['r2']:>10.6f} {cv_r2:>10.6f} {metrics['rmse']:>10.6f}")
        if cv_r2 > best_cv_r2:
            best_cv_r2 = cv_r2
            best_name = name

    print(f"\n  Selected: {best_name} (CV R2 = {best_cv_r2:.6f})")

    best_model = results[best_name]["model"]

    # Save model
    joblib.dump(best_model, MODEL_PATH)
    print(f"  Model saved: {MODEL_PATH}")

    # Save scaler
    joblib.dump(scaler, SCALER_PATH)
    print(f"  Scaler saved: {SCALER_PATH}")

    # Save metadata
    metadata = {
        "model_type": best_name,
        "trained_at": datetime.now().isoformat(),
        "training_data": csv_path,
        "feature_columns": FEATURE_COLUMNS,
        "target_column": TARGET_COLUMN,
        "metrics": {
            name: {k: v for k, v in m.items() if k != "model"}
            for name, m in results.items()
        },
        "selected_model": best_name,
        "selected_cv_r2": best_cv_r2,
    }

    with open(METADATA_PATH, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, default=str)
    print(f"  Metadata saved: {METADATA_PATH}")

    return best_name


def main():
    """Main entry point for model training."""
    parser = argparse.ArgumentParser(description="Train Resume-JD scoring model")
    parser.add_argument(
        "--csv", type=str, default=DEFAULT_CSV,
        help="Path to training data CSV",
    )
    parser.add_argument(
        "--generate", type=int, default=0,
        help="Generate N synthetic training samples before training",
    )
    args = parser.parse_args()

    print("\n" + "=" * 60)
    print("  RESUME-JD SCORING MODEL TRAINER")
    print("=" * 60)

    t_start = time.time()

    # Step 0: Generate synthetic data if requested
    csv_path = args.csv
    if args.generate > 0:
        csv_path = generate_synthetic_training_data(args.generate, csv_path)
    elif not os.path.exists(csv_path):
        print(f"\n  No training data found at: {csv_path}")
        print(f"  Generating 500 synthetic samples as bootstrap...")
        csv_path = generate_synthetic_training_data(500, csv_path)

    # Step 1: Load data
    X, y, df = load_data(csv_path)

    if len(df) < 10:
        print("\n  ERROR: Need at least 10 training samples.")
        print("  Run the pipeline on more resume-JD pairs, or use --generate flag.")
        sys.exit(1)

    # Step 2-4: Train and evaluate
    results, scaler, X_test, y_test = train_and_evaluate(X, y)

    # Step 5: Select and save
    best_name = select_and_save_best(results, scaler, csv_path)

    elapsed = time.time() - t_start
    print(f"\n{'='*60}")
    print(f"  Training complete in {elapsed:.2f}s")
    print(f"  Best model: {best_name}")
    print(f"  Model file: {MODEL_PATH}")
    print(f"  Ready for integration with pipeline.")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
